server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: incident-service
          uri: lb://incident-service
          predicates:
            - Path=/api/incidents/**
        - id: incident-uploads
          uri: lb://incident-service
          predicates:
            - Path=/uploads/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true

jwt:
  secret: mojTajniKljucKojiMoraBitiBasMnogoDugacakZaHS512Algoritam123456789!ABCDEFghijklmnop