server:
  port: 8086

spring:
  application:
    name: nlp-service
  config:
    import: configserver:http://config-server:8888

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
    register-with-eureka: true
    fetch-registry: true